[project]
name = "grpc-typing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "grpcio>=1.75.0",
    "grpcio-tools>=1.75.0",
    "mypy-protobuf>=3.6.0",
]
