# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dummy_pb2 as dummy__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dummy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DummyServiceStub(object):
    """DummyService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UnaryUnary = channel.unary_unary(
                '/dummy.DummyService/UnaryUnary',
                request_serializer=dummy__pb2.DummyRequest.SerializeToString,
                response_deserializer=dummy__pb2.DummyReply.FromString,
                _registered_method=True)
        self.UnaryStream = channel.unary_stream(
                '/dummy.DummyService/UnaryStream',
                request_serializer=dummy__pb2.DummyRequest.SerializeToString,
                response_deserializer=dummy__pb2.DummyReply.FromString,
                _registered_method=True)
        self.StreamUnary = channel.stream_unary(
                '/dummy.DummyService/StreamUnary',
                request_serializer=dummy__pb2.DummyRequest.SerializeToString,
                response_deserializer=dummy__pb2.DummyReply.FromString,
                _registered_method=True)
        self.StreamStream = channel.stream_stream(
                '/dummy.DummyService/StreamStream',
                request_serializer=dummy__pb2.DummyRequest.SerializeToString,
                response_deserializer=dummy__pb2.DummyReply.FromString,
                _registered_method=True)


class DummyServiceServicer(object):
    """DummyService
    """

    def UnaryUnary(self, request, context):
        """UnaryUnary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnaryStream(self, request, context):
        """UnaryStream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamUnary(self, request_iterator, context):
        """StreamUnary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStream(self, request_iterator, context):
        """StreamStream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DummyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UnaryUnary': grpc.unary_unary_rpc_method_handler(
                    servicer.UnaryUnary,
                    request_deserializer=dummy__pb2.DummyRequest.FromString,
                    response_serializer=dummy__pb2.DummyReply.SerializeToString,
            ),
            'UnaryStream': grpc.unary_stream_rpc_method_handler(
                    servicer.UnaryStream,
                    request_deserializer=dummy__pb2.DummyRequest.FromString,
                    response_serializer=dummy__pb2.DummyReply.SerializeToString,
            ),
            'StreamUnary': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamUnary,
                    request_deserializer=dummy__pb2.DummyRequest.FromString,
                    response_serializer=dummy__pb2.DummyReply.SerializeToString,
            ),
            'StreamStream': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamStream,
                    request_deserializer=dummy__pb2.DummyRequest.FromString,
                    response_serializer=dummy__pb2.DummyReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dummy.DummyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dummy.DummyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DummyService(object):
    """DummyService
    """

    @staticmethod
    def UnaryUnary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dummy.DummyService/UnaryUnary',
            dummy__pb2.DummyRequest.SerializeToString,
            dummy__pb2.DummyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnaryStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dummy.DummyService/UnaryStream',
            dummy__pb2.DummyRequest.SerializeToString,
            dummy__pb2.DummyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamUnary(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dummy.DummyService/StreamUnary',
            dummy__pb2.DummyRequest.SerializeToString,
            dummy__pb2.DummyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/dummy.DummyService/StreamStream',
            dummy__pb2.DummyRequest.SerializeToString,
            dummy__pb2.DummyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
